title: SAIV 2026
#preposition: at
description: >-
  The 9th International Symposium on AI Verification in Lisbon on July 24â€“25, 2026
baseurl: /2026 # the subpath of your site, e.g. /blog
url: "https://www.aiverification.org" # the base hostname & protocol for your site, e.g. https://example.com

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"

# Build settings
markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-include-cache
  - jekyll-fa-icons

svg:
  optimize: true

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker

conference:
  # Language
  lang: en

  # Show theme errors:
  show_errors: False

  # Navigation bar
  navigation:
    logo:
      name: SAIV
      img: 'logo.svg'
      #url: ''
    links:
      - name: About
        relative_url: /about/
      # - name: Call for Papers
      #   relative_url: /call/
      - name: Committees
        relative_url: /committees/
      # - name: Program
      #   relative_url: /program/
      # - name: Talks
      #   relative_url: /talks/
      # - name: Speakers & Authors
      #   relative_url: /speakers/
      # - name: Posters
      #   relative_url: /posters/
      #- name: Location
      #  relative_url: /location/
      #- live: true
      - name: Editions
        menu:
        - name: SAIV 2026
          disabled: true
        - name: SAIV 2025
          absolute_url: /2025
        - name: SAIV 2024
          absolute_url: /2024
        - name: FoMLAS 2023
          absolute_url: 'https://fomlas2023.wixsite.com/fomlas2023'
        - name: WOLVERINE 2023
          absolute_url: 'https://wolverine-workshop.github.io/Wolverine2023/'
        - name: FoMLAS 2022
          absolute_url: 'https://fomlas2023.wixsite.com/fomlas2022'
        - name: WOLVERINE 2022
          absolute_url: 'https://wolverine-workshop.github.io/Wolverine2022/'
        - name: FoMLAS 2021
          absolute_url: 'https://fomlas2021.wixsite.com/fomlas2021'
        - name: WOLVERINE 2021
          absolute_url: 'https://wolverine-workshop.github.io/Wolverine2021/'
        - name: FoMLAS 2020
          absolute_url: 'https://fomlas2020.wixsite.com/fomlas2020'
        - name: FoMLAS 2019
          absolute_url: 'https://fomlas2019.wixsite.com/fomlas2019'
        - name: FoMLAS 2018
          absolute_url: 'https://cps-vo.org/node/40531'

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    #img:
      #twitter: 'twitter_preview.png'      # inside /assets/images/
      #open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    logo:
        img: 'logo_full.svg'
    links:
    # - name: Program
    #   disabled: true
    #   relative_url: /program/
    # - name: How to get there
    #   disabled: true
    #   absolute_url: 'XX'
    # - name: Registration
    #   disabled: true
    #   absolute_url: 'XX'
    # - name: Proceedings
    #   disabled: true
    #   absolute_url: 'XX'


  # Information boxes
  #info_bars:
  #  - title: Welcome to the Conference Theme for Jekyll!
  #    color: primary
  #    main_only: true
  #    text: |
  #      The Theme was originally made for the [Winterkongress](https://www.digitale-gesellschaft.ch/kongress/), a yearly conference of the [Digital Society Switzerland](https://digitale-gesellschaft.ch/).
  #
  #      ---
  #
  #      See the [README](github.com/DigitaleGesellschaft/jekyll-theme-conference/) on the project's GitHub repository for further information on how to configure and adapt it to your needs.
  #  - text: This is just some random content for demonstration purposes.
  #    color: warning
  #    pages_only: true

  # Live indications
  #live:
    #date: 21.07.2025
    #timezone: GMT+1
    #stop:       240  # in minutes
    #streaming:
    #  enable: true
      #pause:     60  # in minutes
      #prepend:    5  # in minutes
      #extend:     5  # in minutes
    #demo:
      #enable: false
      #duration: 300  # in seconds
      #pause:     10  # in seconds

  talks:
    ## Talk categories
    main_categories:
      - name: Invited Talk
        color: success
      - name: Presentation
        color: primary
      - name: VNN-COMP
        color: info
      - name: Discussion
        color: warning
      - name: Break
        color: light
      - name: Posters
        color: light
    ## Hide icons on talk overview page
    hide_icons: false

  speakers:
    ## Show first and last name
    show_firstname: true

  #location:
    ## Disable links to locations
    #hide: true
    ## URL of location / room overview page
    #url: '/location'
    ## Main page title shown on location/room navigation bar
    #navbar_title: 'Location'
    ## Show map on location main page.  Set `map: false` if you don't want to
    ## display it.
    #map:
      ## Initial map center point
      #home_coord: 45.801678, 15.973169
      ## Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      ## The following do match the Bootstrap design not too badly:
      ##   - Thunderforest.Neighbourhood
      ##   - Esri.WorldTopoMap
      #map_provider: "OpenStreetMap.Mapnik"
      #default_zoom: 17

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 10 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
